import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profileRouter from "./profile";
import touristRouter from "./tourist";
import trafficRouter from "./traffic";
import wasteRouter from "./waste";
import accessibilityRouter from "./accessibility";
import pointsRouter from "./points";
import dashboardRouter from "./dashboard";
import municipalityRouter from "./municipality";
import storeRouter from "./store";
import eventsRouter from "./events";
import authRouter from "./auth";
import carbonRouter from "./carbon";
import toursRouter from "./tours";
import destinationsRouter from "./destinations";
import suggestionsRouter from "./suggestions";
import complaintsRouter from "./complaints";
import chatbotRouter from "./chatbot";
import fuelRouter from "./fuel";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(profileRouter);
router.use(touristRouter);
router.use(trafficRouter);
router.use(wasteRouter);
router.use(accessibilityRouter);
router.use(pointsRouter);
router.use(dashboardRouter);
router.use(municipalityRouter);
router.use(storeRouter);
router.use(eventsRouter);
router.use(carbonRouter);
router.use(toursRouter);
router.use(destinationsRouter);
router.use(suggestionsRouter);
router.use(complaintsRouter);
router.use(chatbotRouter);
router.use(fuelRouter);

export default router;
